#!/bin/sh
ROOT=$DATA/ubuntu/root
mkdir -p $ROOT
if [ ! -d ~/.ssh ]; then
    echo "No .ssh directory found in home dir, skipping copy."
    exit 0
fi
cp -avr ~/.ssh $ROOT
if [ ! -z "$(ls -A $ROOT/.ssh)" ]; then
    chmod 700 $ROOT/.ssh
    chmod 600 $ROOT/.ssh/*
    chmod 644 $ROOT/.ssh/*.pub
    chmod 644 $ROOT/.ssh/known_hosts
fi
