#!/bin/bash
echo entering chroot
CHROOT="/data/ubuntu"

# read installation dir
if [ -f /etc/enigma2/ubuntucockpit.cfg ]; then
    read -r base_dir < /etc/enigma2/ubuntucockpit.cfg
    CHROOT=$base_dir/ubuntu
else
    echo "Config file not found, using: $CHROOT"
fi

cd $CHROOT/root
$CHROOT/root/mount_chroot

# Cleanup function
cleanup() {
    $CHROOT/root/umount_chroot
}

# execute when exiting..
trap cleanup EXIT

$CHROOT/root/run_chroot
