#!/bin/bash
echo mounting...

CHROOT=/data/ubuntu

mount --bind /dev "$CHROOT/dev"
mount --bind /proc "$CHROOT/proc"
mount --bind /sys "$CHROOT/sys"
mount --bind /run "$CHROOT/run"

mkdir -p $CHROOT/root/git
mount --bind /data/git "$CHROOT/root/git"

if [ ! -d "$CHROOT/dev/pts" ]; then
	mkdir "$CHROOT/dev/pts"
fi
mount -t devpts devpts $CHROOT/dev/pts

cp /etc/resolv.conf $CHROOT/etc/resolv.conf
